language: groovy
jdk:
- oraclejdk8

after_success:
- ./gradlew test jacocoTestReport coveralls -Pcoverage

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/17832ecf3b773c6f015e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
