sudo: false

language: groovy

jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2

env:
  - GRADLE_VERSION=1.12
  - GRADLE_VERSION=2.0
  - GRADLE_VERSION=2.14
  - GRADLE_VERSION=3.0
  - GRADLE_VERSION=3.2

before_install:
  - echo -e "\ndistributionUrl=http\://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
  - cat gradle/wrapper/gradle-wrapper.properties

install:
 - true

script:
  - ./gradlew build --stacktrace --continue

after_success:
  - ./gradlew test jacocoTestReport coveralls -Pcoverage

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/17832ecf3b773c6f015e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
