package com.ofg.uptodate

class Xmls {

    public static String MAVEN_META_DATA_XML = '''\
                                                <metadata>
                                                  <groupId>org.springframework.boot</groupId>
                                                  <artifactId>spring-boot-gradle-plugin</artifactId>
                                                  <version>1.1.5.RELEASE</version>
                                                  <versioning>
                                                    <latest>1.1.5.RELEASE</latest>
                                                    <release>1.1.5.RELEASE</release>
                                                    <versions>
                                                      <version>0.5.0.M1</version>
                                                      <version>0.5.0.M3</version>
                                                      <version>0.5.0.M4</version>
                                                      <version>0.5.0.M5</version>
                                                      <version>0.5.0.M6</version>
                                                      <version>0.5.0.M7</version>
                                                      <version>1.0.0.RC1</version>
                                                      <version>1.0.0.RC2</version>
                                                      <version>1.0.0.RC3</version>
                                                      <version>1.0.0.RC4</version>
                                                      <version>1.0.0.RC5</version>
                                                      <version>1.0.0.RELEASE</version>
                                                      <version>1.0.1.RELEASE</version>
                                                      <version>1.0.2.RELEASE</version>
                                                      <version>1.1.0.M1</version>
                                                      <version>1.1.0.M2</version>
                                                      <version>1.1.0.RC1</version>
                                                      <version>1.1.0.RELEASE</version>
                                                      <version>1.1.1.RELEASE</version>
                                                      <version>1.1.2.RELEASE</version>
                                                      <version>1.1.3.RELEASE</version>
                                                      <version>1.1.4.RELEASE</version>
                                                      <version>1.1.5.RELEASE</version>
                                                    </versions>
                                                    <lastUpdated>20140807211346</lastUpdated>
                                                  </versioning>
                                                </metadata>
                                                '''.stripMargin()

    public static final String HIBERNATE_CORE_META_DATA = '''\
                                                <metadata>
                                                  <groupId>org.hibernate</groupId>
                                                  <artifactId>hibernate-core</artifactId>
                                                  <version>4.3.6.Final</version>
                                                  <versioning>
                                                    <latest>4.3.6.Final</latest>
                                                    <release>4.3.6.Final</release>
                                                    <versions>
                                                      <version>3.3.0.CR1</version>
                                                      <version>3.3.0.CR2</version>
                                                      <version>3.3.0.GA</version>
                                                      <version>3.3.0.SP1</version>
                                                      <version>3.3.1.GA</version>
                                                      <version>3.3.2.GA</version>
                                                      <version>3.5.0-Beta-2</version>
                                                      <version>3.5.0-Beta-3</version>
                                                      <version>3.5.0-Beta-4</version>
                                                      <version>3.5.0-CR-1</version>
                                                      <version>3.5.0-CR-2</version>
                                                      <version>3.5.0.Beta-1</version>
                                                      <version>3.5.0-Final</version>
                                                      <version>3.5.1-Final</version>
                                                      <version>3.5.2-Final</version>
                                                      <version>3.5.3-Final</version>
                                                      <version>3.5.4-Final</version>
                                                      <version>3.5.5-Final</version>
                                                      <version>3.5.6-Final</version>
                                                      <version>3.6.0.Beta1</version>
                                                      <version>3.6.0.Beta2</version>
                                                      <version>3.6.0.Beta3</version>
                                                      <version>3.6.0.Beta4</version>
                                                      <version>3.6.0.CR1</version>
                                                      <version>3.6.0.CR2</version>
                                                      <version>3.6.0.Final</version>
                                                      <version>3.6.1.Final</version>
                                                      <version>3.6.2.Final</version>
                                                      <version>3.6.3.Final</version>
                                                      <version>3.6.4.Final</version>
                                                      <version>3.6.5.Final</version>
                                                      <version>3.6.6.Final</version>
                                                      <version>3.6.7.Final</version>
                                                      <version>3.6.8.Final</version>
                                                      <version>3.6.9.Final</version>
                                                      <version>3.6.10.Final</version>
                                                      <version>4.0.0.Alpha1</version>
                                                      <version>4.0.0.Alpha2</version>
                                                      <version>4.0.0.Alpha3</version>
                                                      <version>4.0.0.Beta1</version>
                                                      <version>4.0.0.Beta2</version>
                                                      <version>4.0.0.Beta3</version>
                                                      <version>4.0.0.Beta4</version>
                                                      <version>4.0.0.Beta5</version>
                                                      <version>4.0.0.CR1</version>
                                                      <version>4.0.0.CR2</version>
                                                      <version>4.0.0.CR3</version>
                                                      <version>4.0.0.CR4</version>
                                                      <version>4.0.0.CR5</version>
                                                      <version>4.0.0.CR6</version>
                                                      <version>4.0.0.CR7</version>
                                                      <version>4.0.0.Final</version>
                                                      <version>4.0.1.Final</version>
                                                      <version>4.1.0.Final</version>
                                                      <version>4.1.1.Final</version>
                                                      <version>4.1.2.Final</version>
                                                      <version>4.1.3.Final</version>
                                                      <version>4.1.4.Final</version>
                                                      <version>4.1.5.Final</version>
                                                      <version>4.1.5.SP1</version>
                                                      <version>4.1.6.Final</version>
                                                      <version>4.1.7.Final</version>
                                                      <version>4.1.8.Final</version>
                                                      <version>4.1.9.Final</version>
                                                      <version>4.1.10.Final</version>
                                                      <version>4.1.11.Final</version>
                                                      <version>4.1.12.Final</version>
                                                      <version>4.2.0.CR1</version>
                                                      <version>4.2.0.CR2</version>
                                                      <version>4.2.0.Final</version>
                                                      <version>4.2.0.SP1</version>
                                                      <version>4.2.1.Final</version>
                                                      <version>4.2.2.Final</version>
                                                      <version>4.2.3.Final</version>
                                                      <version>4.2.4.Final</version>
                                                      <version>4.2.5.Final</version>
                                                      <version>4.2.6.Final</version>
                                                      <version>4.2.7.Final</version>
                                                      <version>4.2.7.SP1</version>
                                                      <version>4.2.8.Final</version>
                                                      <version>4.2.9.Final</version>
                                                      <version>4.2.10.Final</version>
                                                      <version>4.2.11.Final</version>
                                                      <version>4.2.12.Final</version>
                                                      <version>4.2.13.Final</version>
                                                      <version>4.2.14.Final</version>
                                                      <version>4.2.15.Final</version>
                                                      <version>4.3.0.Beta1</version>
                                                      <version>4.3.0.Beta2</version>
                                                      <version>4.3.0.Beta3</version>
                                                      <version>4.3.0.Beta4</version>
                                                      <version>4.3.0.Beta5</version>
                                                      <version>4.3.0.CR1</version>
                                                      <version>4.3.0.CR2</version>
                                                      <version>4.3.0.Final</version>
                                                      <version>4.3.1.Final</version>
                                                      <version>4.3.2.Final</version>
                                                      <version>4.3.3.Final</version>
                                                      <version>4.3.4.Final</version>
                                                      <version>4.3.5.Final</version>
                                                      <version>4.3.6.Final</version>
                                                    </versions>
                                                    <lastUpdated>20140717190500</lastUpdated>
                                                  </versioning>
                                                </metadata>
                                                '''

    public static final String JUNIT_META_DATA = '''\
                                                <metadata>
                                                  <groupId>junit</groupId>
                                                  <artifactId>junit</artifactId>
                                                  <version>4.12-beta-1</version>
                                                  <versioning>
                                                    <latest>4.12-beta-1</latest>
                                                    <release>4.12-beta-1</release>
                                                    <versions>
                                                      <version>3.7</version>
                                                      <version>3.8</version>
                                                      <version>3.8.1</version>
                                                      <version>3.8.2</version>
                                                      <version>4.0</version>
                                                      <version>4.1</version>
                                                      <version>4.2</version>
                                                      <version>4.3</version>
                                                      <version>4.3.1</version>
                                                      <version>4.4</version>
                                                      <version>4.5</version>
                                                      <version>4.6</version>
                                                      <version>4.7</version>
                                                      <version>4.8</version>
                                                      <version>4.8.1</version>
                                                      <version>4.8.2</version>
                                                      <version>4.9</version>
                                                      <version>4.10</version>
                                                      <version>4.11-beta-1</version>
                                                      <version>4.11</version>
                                                      <version>4.12-beta-1</version>
                                                    </versions>
                                                    <lastUpdated>20140727211718</lastUpdated>
                                                  </versioning>
                                                </metadata>
                                                '''.stripMargin()
    
    public static final String OLD_JUNIT_META_DATA = '''\
                                                <metadata>
                                                  <groupId>junit</groupId>
                                                  <artifactId>junit</artifactId>
                                                  <version>3.7</version>
                                                  <versioning>
                                                    <latest>3.7</latest>
                                                    <release>3.7</release>
                                                    <versions>
                                                      <version>3.7</version>
                                                    </versions>
                                                    <lastUpdated>20140727211718</lastUpdated>
                                                  </versioning>
                                                </metadata>
                                                '''.stripMargin()

    public static final String RESPONSE_TEMPLATE = '''\
                                              <metadata>
                                                  <groupId>org.hibernate</groupId>
                                                  <artifactId>hibernate-core</artifactId>
                                                  <version>4.3.6.Final</version>
                                                  <versioning>
                                                    <latest>4.3.6.Final</latest>
                                                    <release>$artifactVersion</release>
                                                    <versions>
                                                    </versions>
                                                    <lastUpdated>20140717190500</lastUpdated>
                                                  </versioning>
                                                </metadata>
                                                '''.stripMargin()

}
